In [1]:
import numpy as np

In [81]:
a = np.arange(0, 49)
a.resize(7,7)
max_size = 5

x = 1
y = 3
window_size = int((max_size - 1) / 2)
left_bound = 7 - max_size if max(0, x - window_size)




0
[[ 0  1  2]
 [ 7  8  9]
 [14 15 16]
 [21 22 23]
 [28 29 30]
 [35 36 37]
 [42 43 44]]
1
[[ 0  1  2  3]
 [ 7  8  9 10]
 [14 15 16 17]
 [21 22 23 24]
 [28 29 30 31]
 [35 36 37 38]
 [42 43 44 45]]
2
[[ 0  1  2  3  4]
 [ 7  8  9 10 11]
 [14 15 16 17 18]
 [21 22 23 24 25]
 [28 29 30 31 32]
 [35 36 37 38 39]
 [42 43 44 45 46]]
3
[[ 1  2  3  4  5]
 [ 8  9 10 11 12]
 [15 16 17 18 19]
 [22 23 24 25 26]
 [29 30 31 32 33]
 [36 37 38 39 40]
 [43 44 45 46 47]]
4
[[ 1  2  3  4  5  6]
 [ 8  9 10 11 12 13]
 [15 16 17 18 19 20]
 [22 23 24 25 26 27]
 [29 30 31 32 33 34]
 [36 37 38 39 40 41]
 [43 44 45 46 47 48]]
5
[[ 1  2  3  4  5  6]
 [ 8  9 10 11 12 13]
 [15 16 17 18 19 20]
 [22 23 24 25 26 27]
 [29 30 31 32 33 34]
 [36 37 38 39 40 41]
 [43 44 45 46 47 48]]
6
[[ 2  3  4  5  6]
 [ 9 10 11 12 13]
 [16 17 18 19 20]
 [23 24 25 26 27]
 [30 31 32 33 34]
 [37 38 39 40 41]
 [44 45 46 47 48]]


2 2
[]
